#!/bin/bash

export GOPATH="$HOME/go"
export GOBIN="$GOPATH/bin"
export PATH="$HOME/.local/bin:$HOME/bin:$GOBIN:/usr/local/bin:$PATH"

"$GOBIN/revive" cmd/main
revive cmd/main
lint_status=$?

if [ "$lint_status" -ne 0 ]; then
    echo "Linting failed. Push rejected."
    exit "$lint_status"
fi

go test ./test
test_status=$?

if [ "$test_status" -ne 0 ]; then
    echo "Test(s) failed. Push rejected."
    exit "$test_status"
fi

exit 0