basePath: /api
definitions:
  handlers.AuthResponse:
    properties:
      message:
        type: string
      statusCode:
        type: integer
    type: object
  handlers.HTTPValidationError:
    properties:
      detail:
        items:
          $ref: '#/definitions/handlers.ValidationError'
        type: array
    type: object
  handlers.ValidationError:
    properties:
      loc:
        items: {}
        type: array
      msg:
        type: string
      type:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: apisupport@genzmonks.com
    name: API Support
    url: https://github.com/GenZM0nks/AscendingMonk
  description: This is a Go rewrite of whoknows.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: AscendingMonkAPI
  version: "1.0"
paths:
  /about:
    get:
      description: Render the about template to show in the browser.
      produces:
      - text/html
      responses:
        "200":
          description: OK
        "500":
          description: error
          schema:
            type: string
      summary: Show about.html
      tags:
      - Pages
  /login:
    get:
      description: Render the Login template to show in the browser.
      produces:
      - text/html
      responses:
        "200":
          description: OK
        "500":
          description: error
          schema:
            type: string
      summary: Show login.html
      tags:
      - Pages
  /register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Register a new user account
      parameters:
      - description: Username
        in: formData
        name: username
        required: true
        type: string
      - description: Email
        in: formData
        name: email
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      - description: Password confirmation
        in: formData
        name: password2
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.AuthResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/handlers.HTTPValidationError'
      summary: Register a new user
      tags:
      - API
swagger: "2.0"
