basePath: /api
definitions:
  handlers.AuthResponse:
    properties:
      message:
        type: string
      statusCode:
        type: integer
    type: object
  handlers.HTTPValidationError:
    properties:
      detail:
        items:
          $ref: '#/definitions/handlers.ValidationError'
        type: array
    type: object
  handlers.StandardResponse:
    properties:
      data:
        $ref: '#/definitions/handlers.WeatherData'
    type: object
  handlers.ValidationError:
    properties:
      loc:
        items: {}
        type: array
      msg:
        type: string
      type:
        type: string
    type: object
  handlers.WeatherData:
    properties:
      days:
        items:
          $ref: '#/definitions/handlers.WeatherDay'
        type: array
      location:
        type: string
    type: object
  handlers.WeatherDay:
    properties:
      date:
        type: string
      precipitationProbability:
        type: integer
      temperatureMaximum:
        type: number
      temperatureMinimum:
        type: number
      weatherCode:
        type: integer
      windDirectionDominant:
        type: integer
      windSpeedMaximum:
        type: number
    type: object
host: localhost:8080
info:
  contact:
    email: apisupport@genzmonks.com
    name: API Support
    url: https://github.com/GenZM0nks/AscendingMonk
  description: This is a Go rewrite of whoknows.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: AscendingMonkAPI
  version: "1.0"
paths:
  /:
    get:
      description: Render the search template to show in the browser.
      produces:
      - text/html
      responses:
        "200":
          description: OK
        "500":
          description: error
          schema:
            type: string
      summary: Show search.html
      tags:
      - Pages
  /about:
    get:
      description: Render the about template to show in the browser.
      produces:
      - text/html
      responses:
        "200":
          description: OK
        "500":
          description: error
          schema:
            type: string
      summary: Show about.html
      tags:
      - Pages
  /api/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Login to an existing user account
      parameters:
      - description: Username
        in: formData
        name: username
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.AuthResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/handlers.HTTPValidationError'
      summary: Login a user
      tags:
      - API
  /api/search:
    get:
      description: Fetch query data from the database.
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: error
          schema:
            type: string
      summary: Fetch query data.
      tags:
      - Pages
  /login:
    get:
      description: Render the Login template to show in the browser.
      produces:
      - text/html
      responses:
        "200":
          description: OK
        "500":
          description: error
          schema:
            type: string
      summary: Show login.html
      tags:
      - Pages
    post:
      description: Accepts a username and password, and compares them to the sqlite
        database.
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "422":
          description: error
          schema:
            type: string
      summary: Show login.html
      tags:
      - queries
  /register:
    get:
      description: Render the Register template to show in the browser.
      produces:
      - text/html
      responses:
        "200":
          description: OK
        "500":
          description: error
          schema:
            type: string
      summary: Show register.html
      tags:
      - Pages
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Register a new user account
      parameters:
      - description: Username
        in: formData
        name: username
        required: true
        type: string
      - description: Email
        in: formData
        name: email
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      - description: Password confirmation
        in: formData
        name: password2
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.AuthResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/handlers.HTTPValidationError'
      summary: Register a new user
      tags:
      - API
  /weather:
    get:
      description: Fetch a seven-day weather forecast for Copenhagen.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.StandardResponse'
        "500":
          description: error
          schema:
            type: string
      summary: Fetch weather forecast.
      tags:
      - API
swagger: "2.0"
